name: Python application

on: [pull_request]

jobs:
  build:
    env:
      PIPENV_NO_INIHERIT: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: ./exemplo
      run: |

        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install -d
        pipenv sync -d
    - name: Link with flake8
      working-directory: ./exemplo
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 .. --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 .. --count --exit-zero --max-complexity=10 --statistics
    - name: Test with pytest
      working-directory: ./exemplo
      run: |
        pipenv run pytest

    - name: Generate coverage report
      working-directory: ./pagamentos
      run: |
        pip install pytest
        pip install pytest-cov
        pipenv run pytest --cov=./pagamentos

      after_sucess:
        pipenv run codecov
